cShareSystems.load_pas("GreatBalancer Map Pack", [
    "coui://ui/mods/GreatBalancer/systems/amaranth_5p ffa system v2.pas",
    "coui://ui/mods/GreatBalancer/systems/aorta_10p system.pas",
    "coui://ui/mods/GreatBalancer/systems/argosso_2vs2 system.pas",
    "coui://ui/mods/GreatBalancer/systems/arkonisa_8p system.pas",
    "coui://ui/mods/GreatBalancer/systems/asura_single 5 vs 5 system.pas",
    "coui://ui/mods/GreatBalancer/systems/asura`s_hulk xvx.pas",
    "coui://ui/mods/GreatBalancer/systems/balrog_6p v2 system.pas",
    "coui://ui/mods/GreatBalancer/systems/boiling_point 3vs3 system v2.pas",
    "coui://ui/mods/GreatBalancer/systems/bubble_8p system v2.pas",
    "coui://ui/mods/GreatBalancer/systems/burma_1vs1 system.pas",
    "coui://ui/mods/GreatBalancer/systems/cataclysm_10p system v3.pas",
    "coui://ui/mods/GreatBalancer/systems/cold_and hot 4p system.pas",
    "coui://ui/mods/GreatBalancer/systems/cosmic_mirror 10p system.pas",
    "coui://ui/mods/GreatBalancer/systems/crusher_5p ffa system.pas",
    "coui://ui/mods/GreatBalancer/systems/dark_and green 4p system.pas",
    "coui://ui/mods/GreatBalancer/systems/deep_space 1vs1 v4 system.pas",
    "coui://ui/mods/GreatBalancer/systems/demon's_mass 1vs1 system.pas",
    "coui://ui/mods/GreatBalancer/systems/devil's_prison 4p system.pas",
    "coui://ui/mods/GreatBalancer/systems/eriko_4p system v1.pas",
    "coui://ui/mods/GreatBalancer/systems/flame_prison 4p system.pas",
    "coui://ui/mods/GreatBalancer/systems/gasoline_4p system.pas",
    "coui://ui/mods/GreatBalancer/systems/green_fathership 6p system.pas",
    "coui://ui/mods/GreatBalancer/systems/green_hills 7p ffa system.pas",
    "coui://ui/mods/GreatBalancer/systems/gregor's_fight 1 vs 1 system.pas",
    "coui://ui/mods/GreatBalancer/systems/hot_maze 4p ffa system.pas",
    "coui://ui/mods/GreatBalancer/systems/jamatra_5vs5 v2 system.pas",
    "coui://ui/mods/GreatBalancer/systems/kalivala_9p system v4.pas",
    "coui://ui/mods/GreatBalancer/systems/krogoth_4vs4 system.pas",
    "coui://ui/mods/GreatBalancer/systems/la_la kill 2 vs 2 system.pas",
    "coui://ui/mods/GreatBalancer/systems/mammoth_6p system.pas",
    "coui://ui/mods/GreatBalancer/systems/minken_good 1vs1 system.pas",
    "coui://ui/mods/GreatBalancer/systems/mistral_3vs3 system.pas",
    "coui://ui/mods/GreatBalancer/systems/moana_4vs4 v4 system.pas",
    "coui://ui/mods/GreatBalancer/systems/moonlight_shadow 5p ffa v2 system.pas",
    "coui://ui/mods/GreatBalancer/systems/navajo_3vs3 system v2.pas",
    "coui://ui/mods/GreatBalancer/systems/northgard_1vs1 system.pas",
    "coui://ui/mods/GreatBalancer/systems/omi_1vs1 system.pas",
    "coui://ui/mods/GreatBalancer/systems/path_of despair 2vs2vs2 system.pas",
    "coui://ui/mods/GreatBalancer/systems/raconidu_3vs3 system.pas",
    "coui://ui/mods/GreatBalancer/systems/ragonot_10p system.pas",
    "coui://ui/mods/GreatBalancer/systems/ragonot_single 10p system.pas",
    "coui://ui/mods/GreatBalancer/systems/riga_1v1 system v2.pas",
    "coui://ui/mods/GreatBalancer/systems/road_to nowhere 4p system v2.pas",
    "coui://ui/mods/GreatBalancer/systems/rongo_2 vs 2 system.pas",
    "coui://ui/mods/GreatBalancer/systems/rongo_greato 8p system.pas",
    "coui://ui/mods/GreatBalancer/systems/ryakonen_easy 7p ffa system.pas",
    "coui://ui/mods/GreatBalancer/systems/ryakonen_hard 7p ffa system v4.pas",
    "coui://ui/mods/GreatBalancer/systems/saga_5vs5 team system v2.pas",
    "coui://ui/mods/GreatBalancer/systems/saga_10p system.pas",
    "coui://ui/mods/GreatBalancer/systems/sandy_battlefield 5p ffa system.pas",
    "coui://ui/mods/GreatBalancer/systems/shadows_and stones 4p system.pas",
    "coui://ui/mods/GreatBalancer/systems/shiny_land 4p system v2.pas",
    "coui://ui/mods/GreatBalancer/systems/shivaxx_8p v1 system.pas",
    "coui://ui/mods/GreatBalancer/systems/shredder's_circle 6p ffa system.pas",
    "coui://ui/mods/GreatBalancer/systems/sleeping_beast 8p system v2.pas",
    "coui://ui/mods/GreatBalancer/systems/stone_in water 6p system.pas",
    "coui://ui/mods/GreatBalancer/systems/treesa_1v1 system.pas",
    "coui://ui/mods/GreatBalancer/systems/tuturama_4vs4 system.pas",
    "coui://ui/mods/GreatBalancer/systems/unona_5p ffa v3 system.pas",
    "coui://ui/mods/GreatBalancer/systems/valley_g 2vs2 system.pas",
    "coui://ui/mods/GreatBalancer/systems/white_raccoon 4vs4 system.pas",
    "coui://ui/mods/GreatBalancer/systems/warlord_8p system.pas",
    "coui://ui/mods/GreatBalancer/systems/waterogeddon_1vs1 system.pas",
    "coui://ui/mods/GreatBalancer/systems/wizard_1vs1 system v2.pas",
    "coui://ui/mods/GreatBalancer/systems/yeti_5vs5 system v2.pas",
]);